application: tailbone
version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
  # add your own custom apps and handlers if you want to extend this
  # - url: /custom/.*
  #   script: custom.app

  # This is the main tailbone restful app handler
  - url: /api/.*
    script: tailbone.restful

  # use this javascript file if you want the bidi databinding abilities
  - url: /tailbone.js
    static_files: tailbone.js
    upload: tailbone.js

  # this is where the bidi javascript posts messages to
  - url: /_bidi
    script: tailbone.bidi

  # this links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  - url: (/?.*)/
    static_files: client/app\1/index.html
    upload: client/app(.*)/index.html
  - url: /
    static_dir: client/app

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

inbound_services:
  - warmup
  - channel_presence

pagespeed:
  disabled_rewriters:
    - LazyloadImages


