application: tailbone
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
  # add your own custom apps and handlers if you want to extend this
  # - url: /custom/.*
  #   script: custom.app

  # use this javascript file if you want the databinding abilities
  - url: /api/tailbone.js
    static_files: tailbone.js
    upload: tailbone.js
  # This is the main tailbone app
  - url: /api/.*
    script: tailbone.app

  # this links everything else in your client/app folder to be served
  - url: (/?.*)/
    static_files: client/app\1/index.html
    upload: client/app(.*)/index.html
  - url: /
    static_dir: client/app

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

inbound_services:
  - warmup
  - channel_presence

pagespeed:
  disabled_rewriters:
    - LazyloadImages


