application: your-app-id
version: master
runtime: python27
api_version: 1
threadsafe: true

handlers:
  # # Add your own custom apps and handlers if you want to extend this
  # - url: /custom/.*
  #   script: custom.app

  # # Allow a proxy util, useful for cross domain resource access
  # - url: /proxy
  #   script: tailbone.proxy

  # This is the main tailbone restful app handler
  - url: /api/.*
    script: tailbone.app

  # use this javascript file if you want the evented databinding abilities
  - url: /tailbone.js
    static_files: tailbone/tailbone.js
    upload: tailbone/tailbone.js
  - url: /_ah/channel/(dis)?connected/
    script: tailbone.connected

  # this links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  - url: (/?.*)/
    static_files: client/app\1/index.html
    upload: client/app(.*)/index.html
  - url: /
    static_dir: client/app

builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

inbound_services:
  - warmup
  - channel_presence

pagespeed:
  enabled_rewriters:
  - MinifyCss
  disabled_rewriters:
  - LazyloadImages
